[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run prisma:migrate:deploy && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
