[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
