[build]
builder = "NIXPACKS"
root = "server"                      
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 100
